[package]
name = "git-fixed-searcher"
version = "0.0.1"
edition = "2024"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
git2 = "0.20.1"
colog = "1.3.0"
log = "0.4.26"
lazy_static = "1.5.0"
regex = "1.11.1"